# Generated by Django 3.1.2 on 2020-11-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
    ]
