# Generated by Django 3.1.2 on 2020-11-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('existencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
    ]
